use std::vec;

use crate::cpu::*;

#[derive(Clone, Copy)]
pub struct Instruction {
    pub name: &'static str,
    pub mode: AddressingMode,
    pub exec: fn(&mut Cpu),
    pub cycles: u8,
}

pub static LOOKUP: [Instruction; 256] = {
    use AddressingMode::*;

    let mut table: [Instruction; 256] = [Instruction {
        name: "???",
        exec: Cpu::lda,
        mode: Implied,
        cycles: 2,
    }; 256];

    #[rustfmt::skip]
    vec![
        Instruction { name:"BRK", exec: Cpu::brk, mode: Immediate, cycles: 7 }, Instruction { name:"ORA", exec: Cpu::ora, mode: IndirectX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 3 }, Instruction { name:"ORA", exec: Cpu::ora, mode: ZeroPage,  cycles: 3 }, Instruction { name:"ASL", exec: Cpu::asl, mode: ZeroPage,  cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"PHP", exec: Cpu::php, mode: Implied, cycles: 3 }, Instruction { name:"ORA", exec: Cpu::ora, mode: Immediate, cycles: 2 }, Instruction { name:"ASL", exec: Cpu::asl, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"ORA", exec: Cpu::ora, mode: Absolute,  cycles: 4 }, Instruction { name:"ASL", exec: Cpu::asl, mode: Absolute,  cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, 
        Instruction { name:"BPL", exec: Cpu::bpl, mode: Relative,  cycles: 2 }, Instruction { name:"ORA", exec: Cpu::ora, mode: IndirectY, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"ORA", exec: Cpu::ora, mode: ZeroPageX, cycles: 4 }, Instruction { name:"ASL", exec: Cpu::asl, mode: ZeroPageX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"CLC", exec: Cpu::clc, mode: Implied, cycles: 2 }, Instruction { name:"ORA", exec: Cpu::ora, mode: AbsoluteY, cycles: 4 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"ORA", exec: Cpu::ora, mode: AbsoluteX, cycles: 4 }, Instruction { name:"ASL", exec: Cpu::asl, mode: AbsoluteX, cycles: 7 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, 
        Instruction { name:"JSR", exec: Cpu::jsr, mode: Absolute,  cycles: 6 }, Instruction { name:"AND", exec: Cpu::and, mode: IndirectX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"BIT", exec: Cpu::bit, mode: ZeroPage,  cycles: 3 }, Instruction { name:"AND", exec: Cpu::and, mode: ZeroPage,  cycles: 3 }, Instruction { name:"ROL", exec: Cpu::rol, mode: ZeroPage,  cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"PLP", exec: Cpu::plp, mode: Implied, cycles: 4 }, Instruction { name:"AND", exec: Cpu::and, mode: Immediate, cycles: 2 }, Instruction { name:"ROL", exec: Cpu::rol, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 2 }, Instruction { name:"BIT", exec: Cpu::bit, mode: Absolute,  cycles: 4 }, Instruction { name:"AND", exec: Cpu::and, mode: Absolute,  cycles: 4 }, Instruction { name:"ROL", exec: Cpu::rol, mode: Absolute,  cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, 
        Instruction { name:"BMI", exec: Cpu::bmi, mode: Relative,  cycles: 2 }, Instruction { name:"AND", exec: Cpu::and, mode: IndirectY, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"AND", exec: Cpu::and, mode: ZeroPageX, cycles: 4 }, Instruction { name:"ROL", exec: Cpu::rol, mode: ZeroPageX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"SEC", exec: Cpu::sec, mode: Implied, cycles: 2 }, Instruction { name:"AND", exec: Cpu::and, mode: AbsoluteY, cycles: 4 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"AND", exec: Cpu::and, mode: AbsoluteX, cycles: 4 }, Instruction { name:"ROL", exec: Cpu::rol, mode: AbsoluteX, cycles: 7 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, 
        Instruction { name:"RTI", exec: Cpu::rti, mode: Implied,   cycles: 6 }, Instruction { name:"EOR", exec: Cpu::eor, mode: IndirectX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 3 }, Instruction { name:"EOR", exec: Cpu::eor, mode: ZeroPage,  cycles: 3 }, Instruction { name:"LSR", exec: Cpu::lsr, mode: ZeroPage,  cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"PHA", exec: Cpu::pha, mode: Implied, cycles: 3 }, Instruction { name:"EOR", exec: Cpu::eor, mode: Immediate, cycles: 2 }, Instruction { name:"LSR", exec: Cpu::lsr, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 2 }, Instruction { name:"JMP", exec: Cpu::jmp, mode: Absolute,  cycles: 3 }, Instruction { name:"EOR", exec: Cpu::eor, mode: Absolute,  cycles: 4 }, Instruction { name:"LSR", exec: Cpu::lsr, mode: Absolute,  cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, 
        Instruction { name:"BVC", exec: Cpu::bvc, mode: Relative,  cycles: 2 }, Instruction { name:"EOR", exec: Cpu::eor, mode: IndirectY, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"EOR", exec: Cpu::eor, mode: ZeroPageX, cycles: 4 }, Instruction { name:"LSR", exec: Cpu::lsr, mode: ZeroPageX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"CLI", exec: Cpu::cli, mode: Implied, cycles: 2 }, Instruction { name:"EOR", exec: Cpu::eor, mode: AbsoluteY, cycles: 4 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"EOR", exec: Cpu::eor, mode: AbsoluteX, cycles: 4 }, Instruction { name:"LSR", exec: Cpu::lsr, mode: AbsoluteX, cycles: 7 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, 
        Instruction { name:"RTS", exec: Cpu::rts, mode: Implied,   cycles: 6 }, Instruction { name:"ADC", exec: Cpu::adc, mode: IndirectX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 3 }, Instruction { name:"ADC", exec: Cpu::adc, mode: ZeroPage,  cycles: 3 }, Instruction { name:"ROR", exec: Cpu::ror, mode: ZeroPage,  cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"PLA", exec: Cpu::pla, mode: Implied, cycles: 4 }, Instruction { name:"ADC", exec: Cpu::adc, mode: Immediate, cycles: 2 }, Instruction { name:"ROR", exec: Cpu::ror, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 2 }, Instruction { name:"JMP", exec: Cpu::jmp, mode: Indirect,  cycles: 5 }, Instruction { name:"ADC", exec: Cpu::adc, mode: Absolute,  cycles: 4 }, Instruction { name:"ROR", exec: Cpu::ror, mode: Absolute,  cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, 
        Instruction { name:"BVS", exec: Cpu::bvs, mode: Relative,  cycles: 2 }, Instruction { name:"ADC", exec: Cpu::adc, mode: IndirectY, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"ADC", exec: Cpu::adc, mode: ZeroPageX, cycles: 4 }, Instruction { name:"ROR", exec: Cpu::ror, mode: ZeroPageX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"SEI", exec: Cpu::sei, mode: Implied, cycles: 2 }, Instruction { name:"ADC", exec: Cpu::adc, mode: AbsoluteY, cycles: 4 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"ADC", exec: Cpu::adc, mode: AbsoluteX, cycles: 4 }, Instruction { name:"ROR", exec: Cpu::ror, mode: AbsoluteX, cycles: 7 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, 
        Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 2 }, Instruction { name:"STA", exec: Cpu::sta, mode: IndirectX, cycles: 6 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"STY", exec: Cpu::sty, mode: ZeroPage,  cycles: 3 }, Instruction { name:"STA", exec: Cpu::sta, mode: ZeroPage,  cycles: 3 }, Instruction { name:"STX", exec: Cpu::stx, mode: ZeroPage,  cycles: 3 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 3 }, Instruction { name:"DEY", exec: Cpu::dey, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 2 }, Instruction { name:"TXA", exec: Cpu::txa, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 2 }, Instruction { name:"STY", exec: Cpu::sty, mode: Absolute,  cycles: 4 }, Instruction { name:"STA", exec: Cpu::sta, mode: Absolute,  cycles: 4 }, Instruction { name:"STX", exec: Cpu::stx, mode: Absolute,  cycles: 4 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 4 }, 
        Instruction { name:"BCC", exec: Cpu::bcc, mode: Relative,  cycles: 2 }, Instruction { name:"STA", exec: Cpu::sta, mode: IndirectY, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"STY", exec: Cpu::sty, mode: ZeroPageX, cycles: 4 }, Instruction { name:"STA", exec: Cpu::sta, mode: ZeroPageX, cycles: 4 }, Instruction { name:"STX", exec: Cpu::stx, mode: ZeroPageY, cycles: 4 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 4 }, Instruction { name:"TYA", exec: Cpu::tya, mode: Implied, cycles: 2 }, Instruction { name:"STA", exec: Cpu::sta, mode: AbsoluteY, cycles: 5 }, Instruction { name:"TXS", exec: Cpu::txs, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 5 }, Instruction { name:"STA", exec: Cpu::sta, mode: AbsoluteX, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, 
        Instruction { name:"LDY", exec: Cpu::ldy, mode: Immediate, cycles: 2 }, Instruction { name:"LDA", exec: Cpu::lda, mode: IndirectX, cycles: 6 }, Instruction { name:"LDX", exec: Cpu::ldx, mode: Immediate, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"LDY", exec: Cpu::ldy, mode: ZeroPage,  cycles: 3 }, Instruction { name:"LDA", exec: Cpu::lda, mode: ZeroPage,  cycles: 3 }, Instruction { name:"LDX", exec: Cpu::ldx, mode: ZeroPage,  cycles: 3 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 3 }, Instruction { name:"TAY", exec: Cpu::tay, mode: Implied, cycles: 2 }, Instruction { name:"LDA", exec: Cpu::lda, mode: Immediate, cycles: 2 }, Instruction { name:"TAX", exec: Cpu::tax, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 2 }, Instruction { name:"LDY", exec: Cpu::ldy, mode: Absolute,  cycles: 4 }, Instruction { name:"LDA", exec: Cpu::lda, mode: Absolute,  cycles: 4 }, Instruction { name:"LDX", exec: Cpu::ldx, mode: Absolute,  cycles: 4 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 4 }, 
        Instruction { name:"BCS", exec: Cpu::bcs, mode: Relative,  cycles: 2 }, Instruction { name:"LDA", exec: Cpu::lda, mode: IndirectY, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"LDY", exec: Cpu::ldy, mode: ZeroPageX, cycles: 4 }, Instruction { name:"LDA", exec: Cpu::lda, mode: ZeroPageX, cycles: 4 }, Instruction { name:"LDX", exec: Cpu::ldx, mode: ZeroPageY, cycles: 4 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 4 }, Instruction { name:"CLV", exec: Cpu::clv, mode: Implied, cycles: 2 }, Instruction { name:"LDA", exec: Cpu::lda, mode: AbsoluteY, cycles: 4 }, Instruction { name:"TSX", exec: Cpu::tsx, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 4 }, Instruction { name:"LDY", exec: Cpu::ldy, mode: AbsoluteX, cycles: 4 }, Instruction { name:"LDA", exec: Cpu::lda, mode: AbsoluteX, cycles: 4 }, Instruction { name:"LDX", exec: Cpu::ldx, mode: AbsoluteY, cycles: 4 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 4 }, 
        Instruction { name:"CPY", exec: Cpu::cpy, mode: Immediate, cycles: 2 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: IndirectX, cycles: 6 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"CPY", exec: Cpu::cpy, mode: ZeroPage,  cycles: 3 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: ZeroPage,  cycles: 3 }, Instruction { name:"DEC", exec: Cpu::dec, mode: ZeroPage,  cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"INY", exec: Cpu::iny, mode: Implied, cycles: 2 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: Immediate, cycles: 2 }, Instruction { name:"DEX", exec: Cpu::dex, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 2 }, Instruction { name:"CPY", exec: Cpu::cpy, mode: Absolute,  cycles: 4 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: Absolute,  cycles: 4 }, Instruction { name:"DEC", exec: Cpu::dec, mode: Absolute,  cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, 
        Instruction { name:"BNE", exec: Cpu::bne, mode: Relative,  cycles: 2 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: IndirectY, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: ZeroPageX, cycles: 4 }, Instruction { name:"DEC", exec: Cpu::dec, mode: ZeroPageX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"CLD", exec: Cpu::cld, mode: Implied, cycles: 2 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: AbsoluteY, cycles: 4 }, Instruction { name:"NOP", exec: Cpu::nop, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"CMP", exec: Cpu::cmp, mode: AbsoluteX, cycles: 4 }, Instruction { name:"DEC", exec: Cpu::dec, mode: AbsoluteX, cycles: 7 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, 
        Instruction { name:"CPX", exec: Cpu::cpx, mode: Immediate, cycles: 2 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: IndirectX, cycles: 6 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"CPX", exec: Cpu::cpx, mode: ZeroPage,  cycles: 3 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: ZeroPage,  cycles: 3 }, Instruction { name:"INC", exec: Cpu::inc, mode: ZeroPage,  cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 5 }, Instruction { name:"INX", exec: Cpu::inx, mode: Implied, cycles: 2 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: Immediate, cycles: 2 }, Instruction { name:"NOP", exec: Cpu::nop, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::sbc, mode: Implied, cycles: 2 }, Instruction { name:"CPX", exec: Cpu::cpx, mode: Absolute,  cycles: 4 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: Absolute,  cycles: 4 }, Instruction { name:"INC", exec: Cpu::inc, mode: Absolute,  cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, 
        Instruction { name:"BEQ", exec: Cpu::beq, mode: Relative,  cycles: 2 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: IndirectY, cycles: 5 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied,   cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 8 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: ZeroPageX, cycles: 4 }, Instruction { name:"INC", exec: Cpu::inc, mode: ZeroPageX, cycles: 6 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 6 }, Instruction { name:"SED", exec: Cpu::sed, mode: Implied, cycles: 2 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: AbsoluteY, cycles: 4 }, Instruction { name:"NOP", exec: Cpu::nop, mode: Implied, cycles: 2 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, Instruction { name:"???", exec: Cpu::nop, mode: Implied,   cycles: 4 }, Instruction { name:"SBC", exec: Cpu::sbc, mode: AbsoluteX, cycles: 4 }, Instruction { name:"INC", exec: Cpu::inc, mode: AbsoluteX, cycles: 7 }, Instruction { name:"???", exec: Cpu::xxx, mode: Implied, cycles: 7 }, 
    
    ];

    table
};
